---
title: "TurnOver"
author:
- Stephanie Hereira, Centro Tlaxcala de Biología de la Conducta, UATx
- Mauricio Hernández, Doctorado en CB, Centro Tlaxcala de Biología de la Conducta, UATx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    theme: spacelab
    highlight: pygments
    toc: yes
    toc_depth: 2
    toc_float: yes
---
# TurnOver q1
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library(tidyverse)
library(ggpubr)

beta <- read.csv("../Data/INTER.csv", header = TRUE, check.names = F)

# Turnover al q=1 order
beta1=subset(beta, q==1)
beta1$DT<- factor(beta1$DT, levels = c("Stomach","Intestine", "Rectum"),
                  labels = c("Stomach", "Small intestine", "Rectum"))


Turnover_q1 <- ggbarplot(subset(beta1, q==1),
                         x= "Non_lethal", y= "Turnover",
                      color = "black",  width = 0.6, lwd=0.3,
                      facet.by = "DT",
                      fill = "Non_lethal",
                      add = "mean_se") +
  labs(x= element_blank(), y = "Ratio of ASVs Turnover") +
  theme_gray() + theme(text = element_text (size = 12)) +
  theme(legend.position = "right",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank())+
  scale_y_continuous(limits = c(0,1))+
 stat_compare_means() +theme(legend.position = "top")
Turnover_q1
#ggsave("Turnover_q1.jpeg", width=6, height=8, dpi=300)

```

# TurnOver q0-q2
```{r, warning=FALSE, message=FALSE, eval=TRUE}

beta0=subset(beta, q == 0)
beta0$DT<- factor(beta0$DT, levels = c("Stomach","Intestine", "Rectum"),
                  labels = c("Stomach", "Small intestine", "Rectum"))

titulo0 <- expression(paste("Ratio of ASVs Turnover (", italic("q"), "=0)"))

turnover0 <- ggbarplot(subset(beta0, q==0), 
                       x= "Non_lethal", y= "Turnover",
                         color = "black",  width = 0.6, lwd=0.3,
                          facet.by = "DT",
                          fill = "Non_lethal",
                         add = "mean_se") +
  labs(x= element_blank(), y = titulo0) +
  theme_gray() + theme(text = element_text (size = 12)) +
  theme(legend.position = "right",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank())+
  scale_y_continuous(limits = c(0,1))+
  geom_signif(test="wilcox.test")+theme(legend.position = "top")

#ggsave("turnover0.jpeg", width=3.8, height=3.5, dpi=300)

beta2=subset(beta, q==2)
beta2$DT<- factor(beta2$DT, levels = c("Stomach","Intestine", "Rectum"),
                  labels = c("Stomach", "Small intestine", "Rectum"))

titulo2 <- expression(paste("Ratio of ASVs Turnover (", italic("q"), "=2)"))

turnover2<- ggbarplot(subset(beta2, q==2), x= "Non_lethal", y= "Turnover",
                    color = "black",  width = 0.6, lwd=0.3,
                    facet.by = "DT",
                    fill = "Non_lethal",
                    add = "mean_se") +
  labs(x= element_blank(), y = titulo2) +
  theme_gray() + theme(text = element_text (size = 12)) +
  theme(legend.position = "right",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank())+
  scale_y_continuous(limits = c(0,1))+
  geom_signif(test="wilcox.test")+theme(legend.position = "none")

#ggsave("turnover2.jpeg", width=3.8, height=3.5, dpi=300)

library(cowplot)
TurnoverFig_q02 <- plot_grid(turnover0,turnover2,
                         nrow = 2,ncol = 1)
#ggsave("TurnoverFig_q02.jpeg", width=6, height=8, dpi=300)
beta %>% ggbarplot(., x= "Non_lethal", y= "Turnover",
          color = "black",  width = 0.6, lwd=0.3,
          facet.by = "DT",
          fill = "Non_lethal",
          add = "mean_se") +
  labs(x= element_blank(), y = "Ratio of ASVs Turnover") +
  theme_gray() + theme(text = element_text (size = 12)) +
  theme(legend.position = "right",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank())+
  scale_y_continuous(limits = c(0,1))+
  geom_signif(test="wilcox.test")+facet_grid(q~DT)

```

